# environent-specific settings will be deep merged with the common hash, overriding values therein

common:
  # Language locale to use, see http://en.wikipedia.org/wiki/ISO_639-1 for list of valid names. The locale is used to lookup a file with the matching name, e.g. translation file "config/locales/en.yml" for locale "en":
  locale: en
  # Timezone to use by default, run `bundle exec rake time:zones:all` to list valid names:
  time_zone: 'Eastern Time (US & Canada)'
  providers:
    - twitter
    - facebook
    - linked_in
    - github
  auth_credentials:
    twitter:
      key: <%= ENV.fetch('TWITTER_KEY') %>
      secret: <%= ENV.fetch('TWITTER_SECRET') %>
    facebook:
      key: <%= ENV.fetch('FB_KEY') %>
      secret: <%= ENV.fetch('FB_SECRET') %>
    linked_in:
      key: <%= ENV.fetch('LINKED_IN_KEY') %>
      secret: <%= ENV.fetch('LINKED_IN_SECRET') %>
    github:
      key: <%= ENV.fetch('GITHUB_KEY') %>
      secret: <%= ENV.fetch('GITHUB_SECRET') %>
  # Sometimes, you'll need to specify the location of your CA certs. Try first without.
  # ssl_ca_path: "/etc/ssl/certs"
  google_analytics_id: 'UA-32099955-1'
  google_analytics_domain: 'madeincincy.com'
  secret_token: <%= ENV.fetch('SESSION_SECRET') %>
  session_cookie_key: _madeincincy_com
  organization:
    name: Made in Cincy
    city: Cincinnati
    state: OH
    url: http://madeincincy.com
    twitter: MadeInCincy
    email: admin@madeincincy.com
    host: heroku.com
    host_url: host@heroku.com
    logotype: <span>Made</span> in <span>Cincy</span>
  mailer:
    # delivery specific settings should be set in environment configs below
    # (you don't want to send out real emails in tests, do you?)
    default_from: contact@madeincincy.com
  search: sql
  mentoring: false # enables experimental mentor matching features

development:
  auth_credentials:
    github:
      key: developmentkey
      secret: devseekrit!
  mailer:
    # passed to ActionMailer (overrides values in config/environments/*.rb)
    # http://edgeguides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
    raise_delivery_errors: false # ActionMailer::Base.raise_delivery_errors = false
    #delivery_method: :smtp       # ActionMailer::Base.delivery_method = :smtp
    #smtp_settings:               # ActionMailer::Base.smtp_settings = { ... }
    #  domain: domain.org
    #  address: smtp.domain.org
    #  port: 25
    #  user_name: smtp_user
    #  password: smtp_password
    #  authentication: plain
